### ISSUE TITLE
Looking for ProblemStatement Feedback

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#1]
Hi Dr.smith,
I created the repository and pushed the files into it. Could u please give me some feedback to my ProblemStatement? 
Thanks!

**Comment by smiths** [comment]
Please remove the text "Put your problem statement here."  You should also delete the comments.

It is unclear what you mean by difference equations.  Is that a different algorithm?

It is unclear from your problem statement whether you have a graphical interface or not.  Your project will be much simpler if you only have a text interface.  Actually, you probably should position your application as a library.

For general purpose tools, like FFT, my preference is usually for a family approach.  Just implementing an FFT algorithm is probably too simple.  Can you come up with a few variabilities, so that we can view the project as a family?

**Comment by smiths** [comment]
Hello @halonazhao .  In case you are still wondering, I thought I would clarify further what I meant by a mathematical library.  Your project is to create a library that contains a family of FFT algorithms. Your goal will be to create a simplified version of something like the gnu scientific library:

https://www.gnu.org/software/gsl/manual/html_node/Fast-Fourier-Transforms.html

Rather than focus on a program that takes input and produces output, you will produce a collection of related subroutines that a calling program would then use. As part of your testing, you will write a calling program (driver), but the deliverable makes more sense as a library.

**Comment by halonazhao** [comment]
Hi Dr. @smiths  . Thanks for the detailed explanation to my questions. I think I can basically understand what I should work for now. And I modified my ProblemStatement.tex file again. Could you please review it? Thanks. This is the link: [https://github.com/741ProjectFFT/FFT/tree/master/Doc/ProblemStatement](url)

**Comment by smiths** [comment]
I am now approving your problem statement.  However, I still had some comments on your tex file.  I have pushed the version of the file with my comments to the repo.
