### ISSUE TITLE
Automated Testing Approach

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#10]
Hello Dr. @smiths,
I am writing the Test Plan. But I am confused about automated testing approach.
Does it say some approaches like using some software to test instead of manual approach to test?

**Comment by smiths** [comment]
Yes, automated means that software runs the tests, instead of a human.  The software runs the test and checks whether the output matches the expected output.  This is usually done using a unit testing framework.  Often a script is used to call the test suite, like using make.  You can see a description of automated testing in Steven Palmer's test plan, as presented today.

**Comment by halonazhao** [comment]
Ok. Thanks~ I'll have a look.
