### ISSUE TITLE
Combine Modules?

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#21]
Hi professor @smiths ，
I feel that I have too many different input modules. But the thing is that they do have their own jobs, although they can be easily achieved but necessary. You said one module can just hide one secrete. I feel I cannot find a good way to combine them to a single input module. Can I just say like:  convert input data into the proper data structure and verify the input parameters and input data meeting the input constraints? This secrete combine the input format module's and input verification module's.

Also, I think I don't need the input parameter module because I don't need parameters to be stored, once they are entered, the library is called directly. Is this right? 

Thanks.

**Comment by smiths** [comment]
Hello @halonazhao.  You need a module for your data structure, but I agree that you do not need an input parameter module.  Your inputs are sequences of numbers.  You can hide this data structure in a module to define the sequence type.  (You will not actually implement the data structure for sequence, but it makes sense for this to be part of your design.)

In class I explained that "one module one secret" is a design heuristic, or rule of thumb.  We might violate the rule, but only with a good reason.  Combining loading data and data verification seems to be a good reason for violating the rule to me.  The reason is that data loading and verification never really occur separately.

**Comment by halonazhao** [comment]
Ok. I see. Thanks.
